### ISSUE TITLE
Emacs interlock files cause an error on startup

### ISSUE THREAD

**Issue by j0ni** [lacarmen/cryogen-core#6]
So the files ignored by default by the new `:ignored-files` configurable include emacs `#.*` files. I kind of thought these were backup/autosave files, but they aren't, they're [interlock](http://www.gnu.org/software/emacs/manual/html_node/emacs/Interlocking.html#Interlocking) files. These are special files, and apparently they can't be `stat`ed.

If such a file exists (for example, if you're editing a template and haven't saved it yet) when you start up the watcher, it barfs with an error which looks like this:

```
Error: /Users/joni/Scratch/clojure/radiculopath/resources/templates/css/.#screen.scss not found
```

This turns out to be `me.raynes.fs/exists?` failing to `stat` the file when attempting a `me.raynes.fs/copy-dir` as part of `cryogen-core.io/copy-resources`.

Though the `:ignored-files` patch prevents the creation of interlock files from triggering a compilation, the pre-existence of such files opens up this bug - and I imagine that you could trigger it by editing a couple of files within the `templates` directory and then saving one of them leaving the other interlock in place.

Right now I don't see a way to deal with this other than re-writing the compiler to copy individual files rather than directories. Definitely I see no way to tell `me.raynes.fs` to deal with interlock files differently.

This is clearly an edge case and it's perfectly possible to work around it, but I'm reporting it to get it bookmarked.

**Comment by yogthos** [comment]
Yeah, I don't think there's a way to supply a mask, might be worth submitting a pr for that to `raynes.fs` at some point. In the meantime, I think writing a custom copy fn should be pretty straightforward. If I recall correctly `file-seq` lists all the files including subfolders, so it would just be a matter of going through them and filtering out the unwanted files before copying. Would be very similar to what [find-assets](https://github.com/lacarmen/cryogen-core/blob/656cc2d0c9fb1042fc4bd19cf51b7b441e5f4a10/src/cryogen_core/io.clj#L16) is doing.

For compiler design ideas I'm good either way, @lacarmen?

**Comment by lacarmen** [comment]
Copying the files rather than the directory would be an easy fix. I looked at `me.raynes.fs` and I didn't see a way to supply a mask either.
